image:
  repository: ghcr.io/kaan-genc/kiwi-postgres
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port:
    http: 80
    https: 8443

ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  host: kiwi.example.org
  tls:
    enabled: false
    port: 443

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

storage:
  persistent: true
  class: longhorn-retain
  size: 15Gi

media:
  root: "/Kiwi/uploads"
  url: "/uploads/"

email:
  from: "kiwi@example.com"
  subject: "[Kiwi-TCMS] "

database:
  type: postgres
  host: 10.190.205.6
  port: 5432
  internal: false
  db_name: kiwitcms
  username: kiwi
  existingSecret: kiwi-secret
