apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kiwi.fullname" . }}-nginx
  labels:
    {{- include "kiwi.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        client_max_body_size 100M;

        location = /healthz {
            access_log off;
            return 200 "ok\n";
            add_header Content-Type text/plain;
        }

        location /static/ {
            alias /Kiwi/static/;
            expires 30d;
            access_log off;
        }

        location /uploads/ {
            alias /Kiwi/uploads/;
        }

        location / {
            include uwsgi_params;

            uwsgi_param HTTP_X_FORWARDED_PROTO https;
            uwsgi_param HTTP_X_FORWARDED_SSL on;
            uwsgi_param HTTPS on;
            uwsgi_param SERVER_PORT 443;
            uwsgi_param HTTP_HOST $host;

            uwsgi_pass unix:/tmp/kiwitcms.sock;
            uwsgi_read_timeout 300;
            uwsgi_send_timeout 300;
        }
    }
