apiVersion: v1
kind: Service
metadata:
  name: {{ include "kiwi.fullname" . }}-https
  labels:
    {{- include "kiwi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: https
      port: {{ .Values.service.port.https | default 443 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "kiwi.selectorLabels" . | nindent 4 }}
